name: Build Mock Relying Party UI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - release*
      - MOSIP*
      - benin-0.11.1-aws

jobs:
  build-docker-mock-ui:
    name: mock-relying-party-ui
    uses: mosip/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: 'mock-relying-party-ui'
      SERVICE_NAME: 'mock-relying-party-ui'
      SQUASH_LAYERS: '10'
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}